FROM archlinux
RUN pacman -Syu --noconfirm \
    && pacman -S --needed --noconfirm htop base-devel git fakeroot nodejs go meson sudo
RUN useradd -m -G wheel vscode
COPY setup-sudo.sh /
RUN bash setup-sudo.sh
RUN rm setup-sudo.sh
