FROM almalinux
RUN yum -y update \
    && yum -y upgrade \
    && yum -y install sudo git golang nodejs cargo java-17-openjdk-devel.x86_64 java-17-openjdk-headless.x86_64 \
    && yum -y groupinstall "Development Tools"
RUN useradd -m -G wheel vscode
COPY setup-sudo.sh /
RUN bash setup-sudo.sh
RUN rm setup-sudo.sh
RUN git clone https://github.com/nvm-sh/nvm
RUN touch /root/.bashrc
RUN su -l vscode -c 'touch .bashrc'
RUN bash nvm/install.sh
RUN su -l vscode -c 'bash /nvm/install.sh'