FROM fedora
RUN dnf -y update \
    && dnf -y install htop sudo git golang nodejs meson cargo java-latest-openjdk-headless java-latest-openjdk-devel \
    && dnf -y groupinstall "Development Tools" "Development Libraries"
RUN useradd -m -G wheel vscode
COPY setup-sudo.sh /
RUN bash setup-sudo.sh
RUN rm setup-sudo.sh
RUN git clone https://github.com/nvm-sh/nvm
RUN touch /root/.bashrc
RUN su -l vscode -c 'touch .bashrc'
RUN bash nvm/install.sh
RUN su -l vscode -c 'bash /nvm/install.sh'