name: Build Experimental image

on: workflow_dispatch

jobs:
  build-gentoo:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Webmin to monitor CPU and RAM usage
      run: |
        sudo apt update
        wget https://prdownloads.sourceforge.net/webadmin/webmin_2.000_all.deb
        sudo apt install ./webmin_2.000_all.deb nodejs
        sudo npm i -g pm2
        echo root:${{ secrets.ROOT_PASSWD }} | sudo chpasswd
        sudo systemctl start webmin
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xf ngrok-v3-stable-linux-amd64.tgz
        sudo cp ngrok /usr/bin
        pm2 start "ngrok tcp --authtoken ${{ secrets.NGROK_WEB_TOKEN }} 10000"
    - name: Build Gentoo image (this will take longer)
      run: |
        docker build experimental/gentoo -f experimental/gentoo/Dockerfile.full -t significant2500/unofficial-github-codespaces-image:full-gentoo-latest
    - name: Time to publish image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWD }}
        docker push significant2500/unofficial-github-codespaces-image:full-gentoo-latest
    - name: If failure ...
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
