name: Build Docker image

on: workflow_dispatch

jobs:
  build-archlinux:
    runs-on: self-hosted
    timeout-minutes: 600
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Arch Linux image
      run: |
        cp setup-sudo.sh archlinux/
        docker build archlinux -f archlinux/Dockerfile.full -t significant2500/unofficial-github-codespaces-image:full-archlinux-rolling
    - name: Time to publish image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWD }}
        docker push significant2500/unofficial-github-codespaces-image:full-archlinux-rolling
    - name: If failure ...
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

  build-fedora:
    runs-on: self-hosted
    timeout-minutes: 600
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Fedora images
      run: |
        cp setup-sudo.sh fedora/
        docker build fedora -f fedora/Dockerfile.full -t significant2500/unofficial-github-codespaces-image:full-fedora-36
    - name: Time to publish image I guess
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWD }}
        docker push significant2500/unofficial-github-codespaces-image:full-fedora-36
    - name: If failure ...
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

  build-almalinux:
    runs-on: self-hosted
    timeout-minutes: 600

    steps:
    - uses: actions/checkout@v2

    - name: Build AlmaLinux images
      run: |
        cp setup-sudo.sh almalinux/
        docker build almalinux -f almalinux/Dockerfile.full -t significant2500/unofficial-github-codespaces-image:full-almalinux-8.5-full
    - name: Time to publish image I guess
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWD }}
        docker push significant2500/unofficial-github-codespaces-image:full-almalinux-8.5-full
    - name: If failure ...
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3