name: Build Docker image

on: workflow_dispatch

jobs:
  build-archlinux-full:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Arch Linux (full) image
      run: |
        cp setup-sudo.sh archlinux/
        docker build archlinux -f archlinux/Dockerfile.full -t significant2500/unofficial-github-codespaces-image:full-archlinux-rolling
    - name: Time to publish image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWD }}
        docker push significant2500/unofficial-github-codespaces-image:full-archlinux-rolling

  build-archlinux-core:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Arch Linux (core) image
      run: |
        cp setup-sudo.sh archlinux/
        docker build archlinux -f archlinux/Dockerfile.core -t significant2500/unofficial-github-codespaces-image:core-archlinux-rolling
    - name: Time to publish image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWD }}
        docker push significant2500/unofficial-github-codespaces-image:core-archlinux-rolling

  build-fedora:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Fedora images
      run: |
        cp setup-sudo.sh fedora/
        docker build fedora -f fedora/Dockerfile.full -t significant2500/unofficial-github-codespaces-image:full-fedora-36
    - name: Time to publish image I guess
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWD }}
        docker push significant2500/unofficial-github-codespaces-image:full-fedora-36

  build-almalinux:
    runs-on: ubuntu-latest
    timeout-minutes: 600

    steps:
    - uses: actions/checkout@v2

    - name: Build AlmaLinux images
      run: |
        cp setup-sudo.sh almalinux/
        docker build almalinux -f almalinux/Dockerfile.full -t significant2500/unofficial-github-codespaces-image:full-almalinux-8.5-full
    - name: Time to publish image I guess
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWD }}
        docker push significant2500/unofficial-github-codespaces-image:full-almalinux-8.5-full

  build-centos-full:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build CentOS 7 image
      run: |
        cp setup-sudo.sh centos/
        cp compile-htop.sh centos/
        docker build centos -f centos/Dockerfile.full -t significant2500/unofficial-github-codespaces-image:full-centos-7
    - name: Time to publish image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWD }}
        docker push significant2500/unofficial-github-codespaces-image:full-centos-7